export const Sourcedata = [
    {
    id:1,
    type:"Animals",
    name:"Bear",
    linkImg:'https://images.unsplash.com/photo-1501446529957-6226bd447c46?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1489&q=80',
    },
    {
        id:2,
        type:"Animals",
        name:"monkey",
        linkImg:'https://images.unsplash.com/photo-1501446529957-6226bd447c46?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1489&q=80',
    },
    {
        id:3,
        type:"Birds",
        name:"peacock",
        linkImg:"https://www.pexels.com/photo/a-peacock-perched-on-stone-fence-4475253/,"
    },
    { id:4,
        type:"Birds",
        name:"pigeon",
        linkImg:"https://www.pexels.com/photo/white-dove-on-brown-surface-under-blue-sky-75973/",
    },
    {
        id:5,
        type:"Animals",
        name:"cheetah",
        linkImg:"https://www.pexels.com/photo/speed-predator-cheetah-wild-animal-59952/",
    },
    {   id:6,
        type:"Flowers",
        name:"rose",
        linkImg:"https://www.pexels.com/photo/red-rose-bush-one-rose-62332/",
    },
    {
        id:7,
        type:"Flowers",
        name:"lotus",
        linkImg:"https://www.pexels.com/photo/pink-water-lily-flower-on-water-539694/",
    },
    {
        id:8,
        type:"Flowers",
        name:"Hibiscus",
        linkImg:"https://www.pexels.com/photo/selective-focus-photography-of-pink-petaled-flower-244796/",
    }
    
]